using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DuoBoxApiClient.Models {
    public class Boleto {
        public string _0 { get; set; }
        public string id { get; set; }
        public string _1 { get; set; }
        public string usuarios_id { get; set; }
        public string _2 { get; set; }
        public string contas_id { get; set; }
        public string _3 { get; set; }
        public string plano_contas_id { get; set; }
        public string _4 { get; set; }
        public string contas_movimentacao_subcategoria_id { get; set; }
        public string _5 { get; set; }
        public string contas_movimentacao_tipo_pagamento_id { get; set; }
        public string _6 { get; set; }
        public string forma_recebimento_id { get; set; }
        public string _7 { get; set; }
        public string moedas_id { get; set; }
        public string _8 { get; set; }
        public string cadastro_tipo { get; set; }
        public string _9 { get; set; }
        public string cadastro_id { get; set; }
        public string _10 { get; set; }
        public string origem_tipo { get; set; }
        public string _11 { get; set; }
        public string origem_id { get; set; }
        public string _12 { get; set; }
        public string documento_tipo { get; set; }
        public string _13 { get; set; }
        public string documento_id { get; set; }
        public string _14 { get; set; }
        public string transferencia_id { get; set; }
        public string _15 { get; set; }
        public string descricao { get; set; }
        public string _16 { get; set; }
        public string data_lancamento { get; set; }
        public string _17 { get; set; }
        public string data_vencimento { get; set; }
        public object _18 { get; set; }
        public object data_agendamento { get; set; }
        public string _19 { get; set; }
        public string valor { get; set; }
        public string _20 { get; set; }
        public string tipo { get; set; }
        public string _21 { get; set; }
        public string numero_documento { get; set; }
        public string _22 { get; set; }
        public string observacao { get; set; }
        public string _23 { get; set; }
        public string situacao { get; set; }
        public string _24 { get; set; }
        public string data_pagamento { get; set; }
        public string _25 { get; set; }
        public string data_credito_conta { get; set; }
        public string _26 { get; set; }
        public string data_hora_baixa { get; set; }
        public string _27 { get; set; }
        public string pagamento_usuarios_id { get; set; }
        public string _28 { get; set; }
        public string valor_juros { get; set; }
        public string _29 { get; set; }
        public string valor_multa { get; set; }
        public string _30 { get; set; }
        public string valor_outros { get; set; }
        public string _31 { get; set; }
        public string valor_desconto { get; set; }
        public string _32 { get; set; }
        public string valor_total { get; set; }
        public string _33 { get; set; }
        public string parcelas_total { get; set; }
        public string _34 { get; set; }
        public string parcela_numero { get; set; }
        public string _35 { get; set; }
        public string parcela_pai_id { get; set; }
        public string _36 { get; set; }
        public string alterado { get; set; }
        public string _37 { get; set; }
        public string nosso_numero { get; set; }
        public string _38 { get; set; }
        public string _39 { get; set; }
        public string _40 { get; set; }
        public string em_observacao { get; set; }
        public string _41 { get; set; }
        public string referencia_mensalidade { get; set; }
        public object _42 { get; set; }
        public string referencia { get; set; }
        public string _43 { get; set; }
        public string ordens_servicos_id { get; set; }
        public string _44 { get; set; }
        public string impresso { get; set; }
        public string _45 { get; set; }
        public string banco_multa { get; set; }
        public string _46 { get; set; }
        public string banco_juros_dia { get; set; }
        public string _47 { get; set; }
        public string servico_nome { get; set; }
        public string _48 { get; set; }
        public string cli_id { get; set; }
        public string _49 { get; set; }
        public string cli_nome { get; set; }
        public string _50 { get; set; }
        public string cli_telefone { get; set; }
        public string _51 { get; set; }
        public string cli_celular { get; set; }
        public string _52 { get; set; }
        public string servico_status { get; set; }
        public string _53 { get; set; }
        public string servico_ativo { get; set; }
        public string status { get; set; }
        public int vencido { get; set; }
        public string valor_atualizado { get; set; }
        public object valor_documento_novo { get; set; }
        public string valor_pago { get; set; }
        public string linha_digitavel { get; set; }
        public string link_boleto { get; set; }
    }
}
